---

- name: 'Installation et configuration de golang-myip'
  hosts: default
  become: true

  tasks:

    - name: creation d'un fichier tampon
      file:
        path: ~/tampon.txt
        state: touch

    - name: ajout des cles ssh
      shell: curl -o ~/tampon.txt https://github.com/BastienBalaud.keys

    - name: copie des cles
      shell: cat ~/tampon.txt >> ~/.ssh/authorized_keys

    - name: suppression du fichier tampon
      file:
        path: ~/tampon.txt
        state: absent

    - name: installation de go
      dnf:
        name: go
        state: latest

    - name: installation de make
      dnf:
        name: make
        state: latest

    - name: installation de git
      dnf:
        name: git
        state: latest

    - name: copie du repo git
      git:
        repo: https://github.com/BastienBalaud/golang-myip.git
        dest: /opt/golang-myip/
        clone: yes
        update: yes

    - name: compilation
      shell: make
      args:
        chdir: /opt/golang-myip/

    - name: creation du fichier init
      file:
        path: /etc/systemd/system/myip.service
        state: touch

    - name: ajout du contenu du fichier
      blockinfile:
        path: /etc/systemd/system/myip.service
        block: |
          [Unit]
          Description=Je suis un joli service qui te donne ton IP
          [Service]
          Type=simple
          ExecStart=/opt/golang-myip/build/server.x86_64 --port 80
          ExecReload=/opt/golang-myip/build/server.x86_64 --port 80
          [Install]
          WantedBy=multi-user.target

    - name: demarrage du service myip + enabled
      service:
        name: myip
        state: started
        enabled: yes

    - name: vérification du service myip
      shell: systemctl status myip 

    - name: verification de l'etat du service myip
      shell: systemctl status myip

    - name: requete http
      uri:
        url: http://127.0.0.1:80

